service: my-express-serverless

provider:
  name: aws
  runtime: nodejs20.x
  # stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/app.handler
    events:
      - http: 
          path: api/v1/test
          method: get
      - http: 
          path: api/v1/test
          method: post
          cors: true
      - http: 
          path: api/v1/test2
          method: get

plugins:
  # - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3600
